### ISSUE TITLE
Docker image is not update after remote url PR is merged 

### ISSUE THREAD

**Issue by Gourav2906** [open-fresh/avalanche#9]
https://quay.io/repository/freshtracks.io/avalanche is not updated from last one year
the change I am looking for https://github.com/open-fresh/avalanche/pull/5

**Comment by Gourav2906** [comment]
@csmarchbanks

**Comment by csmarchbanks** [comment]
I just pushed out a new `:latest` tag to that repo, let me know if that does not work for you.

I would love to add CI for this project, and likely move the repo from freshtracks.io to open-fresh, but have not had the time yet.
